# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci
# IP: The module: 'jtag_mac_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci
# IP: The module: 'jtag_mac_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/llillo/Desktop/cosas_ordenadas/uni/memoria/fcc/HDL_original/Gold_Ref_22_14/fcc_fixpt_fil/fpgaproj/fcc_fixpt_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_mac_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
