// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fcc_fcc,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.797125,HLS_SYN_LAT=10,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=296,HLS_SYN_LUT=1118,HLS_VERSION=2024_1}" *)

module fcc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Vfcref,
        Vfc,
        Voutref,
        Vout,
        D1,
        D1_ap_vld,
        D2,
        D2_ap_vld,
        ui,
        ui_ap_vld,
        uv,
        uv_ap_vld
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] Vfcref;
input  [15:0] Vfc;
input  [15:0] Voutref;
input  [15:0] Vout;
output  [6:0] D1;
output   D1_ap_vld;
output  [6:0] D2;
output   D2_ap_vld;
output  [6:0] ui;
output   ui_ap_vld;
output  [6:0] uv;
output   uv_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg D1_ap_vld;
reg D2_ap_vld;
reg ui_ap_vld;
reg uv_ap_vld;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [21:0] pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik;
reg   [20:0] pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik;
reg  signed [21:0] pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik;
reg   [20:0] pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik;
wire   [35:0] mul_ln44_1_fu_236_p2;
reg  signed [35:0] mul_ln44_1_reg_1626;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire  signed [21:0] select_ln44_fu_355_p3;
reg  signed [21:0] select_ln44_reg_1636;
wire    ap_CS_fsm_state4;
wire  signed [21:0] select_ln44_1_fu_446_p3;
reg  signed [21:0] select_ln44_1_reg_1641;
wire   [21:0] add_ln47_fu_536_p2;
reg   [21:0] add_ln47_reg_1646;
wire    ap_CS_fsm_state8;
wire   [0:0] and_ln47_3_fu_669_p2;
reg   [0:0] and_ln47_3_reg_1651;
wire   [0:0] or_ln47_1_fu_693_p2;
reg   [0:0] or_ln47_1_reg_1656;
wire   [21:0] add_ln47_1_fu_733_p2;
reg   [21:0] add_ln47_1_reg_1661;
wire   [0:0] and_ln47_9_fu_866_p2;
reg   [0:0] and_ln47_9_reg_1666;
wire   [0:0] or_ln47_3_fu_890_p2;
reg   [0:0] or_ln47_3_reg_1671;
wire   [20:0] ui_aux_fu_941_p3;
reg   [20:0] ui_aux_reg_1676;
wire    ap_CS_fsm_state9;
wire  signed [20:0] uv_aux_fu_998_p3;
reg  signed [20:0] uv_aux_reg_1681;
reg   [0:0] tmp_34_reg_1686;
reg   [6:0] trunc_ln5_reg_1693;
reg   [0:0] tmp_35_reg_1698;
wire   [0:0] tmp_22_fu_1135_p3;
reg   [0:0] tmp_22_reg_1703;
wire    ap_CS_fsm_state10;
wire   [6:0] add_ln59_1_fu_1195_p2;
reg   [6:0] add_ln59_1_reg_1709;
wire   [0:0] or_ln59_1_fu_1259_p2;
reg   [0:0] or_ln59_1_reg_1716;
wire   [0:0] and_ln59_1_fu_1265_p2;
reg   [0:0] and_ln59_1_reg_1722;
wire   [0:0] tmp_26_fu_1277_p3;
reg   [0:0] tmp_26_reg_1728;
wire   [6:0] add_ln60_fu_1337_p2;
reg   [6:0] add_ln60_reg_1734;
wire   [0:0] or_ln60_1_fu_1401_p2;
reg   [0:0] or_ln60_1_reg_1741;
wire   [0:0] and_ln60_1_fu_1407_p2;
reg   [0:0] and_ln60_1_reg_1747;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
wire   [13:0] mul_ln44_1_fu_236_p1;
wire  signed [20:0] sext_ln44_2_fu_246_p0;
wire  signed [20:0] tmp_13_fu_250_p1;
wire   [24:0] tmp_13_fu_250_p3;
wire  signed [26:0] sext_ln44_5_fu_258_p1;
wire   [26:0] sub_ln44_fu_262_p2;
wire  signed [26:0] sext_ln44_2_fu_246_p1;
wire  signed [26:0] sub_ln44_1_fu_268_p2;
wire  signed [35:0] grp_fu_1565_p3;
wire   [0:0] tmp_1_fu_294_p3;
wire   [21:0] trunc_ln_fu_285_p4;
wire   [21:0] zext_ln44_1_fu_301_p1;
wire   [21:0] add_ln44_1_fu_305_p2;
wire   [0:0] tmp_fu_278_p3;
wire   [0:0] tmp_4_fu_311_p3;
wire   [0:0] xor_ln44_fu_319_p2;
wire   [0:0] or_ln44_fu_325_p2;
wire   [0:0] xor_ln44_1_fu_331_p2;
wire   [0:0] xor_ln44_2_fu_337_p2;
wire   [0:0] or_ln44_1_fu_343_p2;
wire   [0:0] and_ln44_fu_349_p2;
wire  signed [35:0] grp_fu_1575_p3;
wire   [0:0] tmp_15_fu_385_p3;
wire   [21:0] trunc_ln44_3_fu_376_p4;
wire   [21:0] zext_ln44_2_fu_392_p1;
wire   [21:0] add_ln44_3_fu_396_p2;
wire   [0:0] tmp_14_fu_369_p3;
wire   [0:0] tmp_16_fu_402_p3;
wire   [0:0] xor_ln44_3_fu_410_p2;
wire   [0:0] or_ln44_2_fu_416_p2;
wire   [0:0] xor_ln44_4_fu_422_p2;
wire   [0:0] xor_ln44_5_fu_428_p2;
wire   [0:0] or_ln44_3_fu_434_p2;
wire   [0:0] and_ln44_1_fu_440_p2;
wire   [16:0] zext_ln47_fu_460_p1;
wire   [16:0] zext_ln47_1_fu_464_p1;
wire  signed [16:0] sub_ln47_fu_468_p2;
wire   [16:0] zext_ln47_3_fu_481_p1;
wire   [16:0] zext_ln47_4_fu_485_p1;
wire  signed [16:0] sub_ln47_2_fu_489_p2;
wire  signed [39:0] grp_fu_1586_p3;
wire   [0:0] tmp_8_fu_518_p3;
wire   [21:0] trunc_ln47_1_fu_509_p4;
wire   [21:0] zext_ln47_2_fu_532_p1;
wire   [0:0] tmp_10_fu_542_p3;
wire   [0:0] tmp_9_fu_525_p3;
wire   [0:0] xor_ln47_fu_550_p2;
wire   [2:0] tmp_2_fu_569_p4;
wire   [3:0] tmp_3_fu_584_p4;
wire   [0:0] and_ln47_fu_556_p2;
wire   [0:0] icmp_ln47_1_fu_593_p2;
wire   [0:0] icmp_ln47_2_fu_599_p2;
wire   [0:0] tmp_11_fu_562_p3;
wire   [0:0] icmp_ln47_fu_578_p2;
wire   [0:0] xor_ln47_1_fu_613_p2;
wire   [0:0] and_ln47_1_fu_619_p2;
wire   [0:0] and_ln47_2_fu_633_p2;
wire   [0:0] tmp_5_fu_502_p3;
wire   [0:0] xor_ln47_2_fu_639_p2;
wire   [0:0] select_ln47_fu_605_p3;
wire   [0:0] xor_ln47_3_fu_651_p2;
wire   [0:0] or_ln47_fu_657_p2;
wire   [0:0] xor_ln47_4_fu_663_p2;
wire   [0:0] select_ln47_1_fu_625_p3;
wire   [0:0] and_ln47_4_fu_675_p2;
wire   [0:0] empty_fu_645_p2;
wire   [0:0] xor_ln47_5_fu_681_p2;
wire   [0:0] and_ln47_5_fu_687_p2;
wire  signed [41:0] grp_fu_1601_p3;
wire   [0:0] tmp_18_fu_715_p3;
wire   [21:0] trunc_ln47_3_fu_706_p4;
wire   [21:0] zext_ln47_5_fu_729_p1;
wire   [0:0] tmp_20_fu_739_p3;
wire   [0:0] tmp_19_fu_722_p3;
wire   [0:0] xor_ln47_6_fu_747_p2;
wire   [4:0] tmp_6_fu_766_p4;
wire   [5:0] tmp_7_fu_781_p4;
wire   [0:0] and_ln47_6_fu_753_p2;
wire   [0:0] icmp_ln47_4_fu_790_p2;
wire   [0:0] icmp_ln47_5_fu_796_p2;
wire   [0:0] tmp_21_fu_759_p3;
wire   [0:0] icmp_ln47_3_fu_775_p2;
wire   [0:0] xor_ln47_7_fu_810_p2;
wire   [0:0] and_ln47_7_fu_816_p2;
wire   [0:0] and_ln47_8_fu_830_p2;
wire   [0:0] tmp_17_fu_699_p3;
wire   [0:0] xor_ln47_8_fu_836_p2;
wire   [0:0] select_ln47_4_fu_802_p3;
wire   [0:0] xor_ln47_9_fu_848_p2;
wire   [0:0] or_ln47_2_fu_854_p2;
wire   [0:0] xor_ln47_10_fu_860_p2;
wire   [0:0] select_ln47_5_fu_822_p3;
wire   [0:0] and_ln47_10_fu_872_p2;
wire   [0:0] empty_14_fu_842_p2;
wire   [0:0] xor_ln47_11_fu_878_p2;
wire   [0:0] and_ln47_11_fu_884_p2;
wire   [21:0] select_ln47_2_fu_896_p3;
wire   [21:0] select_ln47_3_fu_903_p3;
wire   [0:0] icmp_ln50_fu_913_p2;
wire   [0:0] tmp_12_fu_919_p3;
wire   [0:0] or_ln50_fu_935_p2;
wire   [20:0] select_ln50_fu_927_p3;
wire   [20:0] trunc_ln50_fu_909_p1;
wire   [21:0] select_ln47_6_fu_955_p3;
wire   [21:0] select_ln47_7_fu_962_p3;
wire   [0:0] icmp_ln50_1_fu_972_p2;
wire   [0:0] icmp_ln50_2_fu_978_p2;
wire   [0:0] or_ln50_1_fu_992_p2;
wire   [20:0] select_ln50_1_fu_984_p3;
wire   [20:0] trunc_ln50_1_fu_968_p1;
wire   [0:0] tmp_31_fu_1022_p3;
wire   [6:0] trunc_ln4_fu_1012_p4;
wire   [6:0] zext_ln67_fu_1038_p1;
wire   [6:0] add_ln67_fu_1042_p2;
wire   [0:0] tmp_32_fu_1030_p3;
wire   [0:0] tmp_33_fu_1048_p3;
wire   [0:0] not_tmp_38_fu_1056_p2;
wire   [0:0] xor_ln67_fu_1068_p2;
wire   [0:0] empty_21_fu_1062_p2;
wire   [0:0] and_ln67_fu_1074_p2;
wire   [6:0] select_ln67_fu_1080_p3;
wire  signed [22:0] sext_ln59_fu_1126_p1;
wire   [22:0] zext_ln59_1_fu_1123_p1;
wire   [22:0] add_ln59_fu_1129_p2;
wire   [12:0] trunc_ln59_fu_1161_p1;
wire   [0:0] tmp_23_fu_1153_p3;
wire   [0:0] icmp_ln59_fu_1165_p2;
wire   [0:0] or_ln59_fu_1179_p2;
wire   [0:0] and_ln59_fu_1185_p2;
wire   [6:0] trunc_ln2_fu_1143_p4;
wire   [6:0] zext_ln59_fu_1191_p1;
wire   [1:0] tmp_s_fu_1201_p4;
wire   [0:0] tmp_25_fu_1223_p3;
wire   [0:0] icmp_ln59_2_fu_1217_p2;
wire   [0:0] icmp_ln59_1_fu_1211_p2;
wire   [0:0] tmp_24_fu_1171_p3;
wire   [0:0] xor_ln59_fu_1231_p2;
wire   [0:0] select_ln59_fu_1237_p3;
wire   [0:0] empty_16_fu_1251_p3;
wire   [0:0] empty_15_fu_1245_p2;
wire   [22:0] sub_ln60_fu_1271_p2;
wire   [12:0] trunc_ln60_fu_1303_p1;
wire   [0:0] tmp_27_fu_1295_p3;
wire   [0:0] icmp_ln60_fu_1307_p2;
wire   [0:0] or_ln60_fu_1321_p2;
wire   [0:0] and_ln60_fu_1327_p2;
wire   [6:0] trunc_ln3_fu_1285_p4;
wire   [6:0] zext_ln60_fu_1333_p1;
wire   [1:0] tmp_29_fu_1343_p4;
wire   [0:0] tmp_30_fu_1365_p3;
wire   [0:0] icmp_ln60_2_fu_1359_p2;
wire   [0:0] icmp_ln60_1_fu_1353_p2;
wire   [0:0] tmp_28_fu_1313_p3;
wire   [0:0] xor_ln60_fu_1373_p2;
wire   [0:0] select_ln60_fu_1379_p3;
wire   [0:0] empty_19_fu_1393_p3;
wire   [0:0] empty_18_fu_1387_p2;
wire   [6:0] zext_ln68_fu_1413_p1;
wire   [6:0] add_ln68_fu_1416_p2;
wire   [0:0] tmp_36_fu_1421_p3;
wire   [0:0] xor_ln68_fu_1429_p2;
wire   [0:0] empty_22_fu_1435_p2;
wire   [6:0] select_ln68_fu_1440_p3;
wire   [0:0] or_ln68_1_fu_1448_p2;
wire   [6:0] empty_23_fu_1453_p3;
wire   [0:0] xor_ln59_2_fu_1474_p2;
wire   [0:0] or_ln59_2_fu_1485_p2;
wire   [0:0] xor_ln59_1_fu_1469_p2;
wire   [6:0] select_ln59_1_fu_1479_p3;
wire   [6:0] empty_17_fu_1496_p3;
wire   [0:0] brmerge2571_fu_1490_p2;
wire   [6:0] select_ln59_2_fu_1502_p3;
wire   [0:0] xor_ln60_2_fu_1522_p2;
wire   [0:0] or_ln60_2_fu_1533_p2;
wire   [0:0] xor_ln60_1_fu_1517_p2;
wire   [6:0] select_ln60_1_fu_1527_p3;
wire   [6:0] empty_20_fu_1544_p3;
wire   [0:0] brmerge3083_fu_1538_p2;
wire   [6:0] select_ln60_2_fu_1550_p3;
wire   [20:0] grp_fu_1565_p0;
wire  signed [12:0] grp_fu_1565_p1;
wire   [13:0] grp_fu_1575_p1;
wire   [15:0] grp_fu_1586_p2;
wire   [17:0] grp_fu_1601_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire   [33:0] grp_fu_1565_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik = 22'd0;
#0 pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik = 21'd0;
#0 pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik = 22'd0;
#0 pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik = 21'd0;
end

fcc_mul_22s_14ns_36_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 36 ))
mul_22s_14ns_36_1_1_U1(
    .din0(pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik),
    .din1(mul_ln44_1_fu_236_p1),
    .dout(mul_ln44_1_fu_236_p2)
);

fcc_mac_muladd_21ns_13s_36s_36_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
mac_muladd_21ns_13s_36s_36_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1565_p0),
    .din1(grp_fu_1565_p1),
    .din2(mul_ln44_1_reg_1626),
    .ce(1'b1),
    .dout(grp_fu_1565_p3)
);

fcc_mac_muladd_22s_14ns_27s_36_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 36 ))
mac_muladd_22s_14ns_27s_36_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik),
    .din1(grp_fu_1575_p1),
    .din2(sub_ln44_1_fu_268_p2),
    .ce(1'b1),
    .dout(grp_fu_1575_p3)
);

fcc_am_submul_17s_22s_16ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 22 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 40 ))
am_submul_17s_22s_16ns_40_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln47_fu_468_p2),
    .din1(select_ln44_reg_1636),
    .din2(grp_fu_1586_p2),
    .ce(1'b1),
    .dout(grp_fu_1586_p3)
);

fcc_am_submul_17s_22s_18ns_42_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 22 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 42 ))
am_submul_17s_22s_18ns_42_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln47_2_fu_489_p2),
    .din1(select_ln44_1_reg_1641),
    .din2(grp_fu_1601_p2),
    .ce(1'b1),
    .dout(grp_fu_1601_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik <= 21'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik <= uv_aux_fu_998_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik <= 22'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik <= select_ln44_1_fu_446_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik <= 21'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik <= ui_aux_fu_941_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik <= 22'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xXik <= select_ln44_fu_355_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln47_1_reg_1661 <= add_ln47_1_fu_733_p2;
        add_ln47_reg_1646 <= add_ln47_fu_536_p2;
        and_ln47_3_reg_1651 <= and_ln47_3_fu_669_p2;
        and_ln47_9_reg_1666 <= and_ln47_9_fu_866_p2;
        or_ln47_1_reg_1656 <= or_ln47_1_fu_693_p2;
        or_ln47_3_reg_1671 <= or_ln47_3_fu_890_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln59_1_reg_1709 <= add_ln59_1_fu_1195_p2;
        add_ln60_reg_1734 <= add_ln60_fu_1337_p2;
        and_ln59_1_reg_1722 <= and_ln59_1_fu_1265_p2;
        and_ln60_1_reg_1747 <= and_ln60_1_fu_1407_p2;
        or_ln59_1_reg_1716 <= or_ln59_1_fu_1259_p2;
        or_ln60_1_reg_1741 <= or_ln60_1_fu_1401_p2;
        tmp_22_reg_1703 <= add_ln59_fu_1129_p2[32'd22];
        tmp_26_reg_1728 <= sub_ln60_fu_1271_p2[32'd22];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mul_ln44_1_reg_1626 <= mul_ln44_1_fu_236_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        select_ln44_1_reg_1641 <= select_ln44_1_fu_446_p3;
        select_ln44_reg_1636 <= select_ln44_fu_355_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_34_reg_1686 <= uv_aux_fu_998_p3[32'd20];
        tmp_35_reg_1698 <= uv_aux_fu_998_p3[32'd13];
        trunc_ln5_reg_1693 <= {{uv_aux_fu_998_p3[20:14]}};
        ui_aux_reg_1676 <= ui_aux_fu_941_p3;
        uv_aux_reg_1681 <= uv_aux_fu_998_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        D1_ap_vld = 1'b1;
    end else begin
        D1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        D2_ap_vld = 1'b1;
    end else begin
        D2_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ui_ap_vld = 1'b1;
    end else begin
        ui_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        uv_ap_vld = 1'b1;
    end else begin
        uv_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign D1 = ((brmerge2571_fu_1490_p2[0:0] == 1'b1) ? select_ln59_2_fu_1502_p3 : add_ln59_1_reg_1709);

assign D2 = ((brmerge3083_fu_1538_p2[0:0] == 1'b1) ? select_ln60_2_fu_1550_p3 : add_ln60_reg_1734);

assign add_ln44_1_fu_305_p2 = (trunc_ln_fu_285_p4 + zext_ln44_1_fu_301_p1);

assign add_ln44_3_fu_396_p2 = (trunc_ln44_3_fu_376_p4 + zext_ln44_2_fu_392_p1);

assign add_ln47_1_fu_733_p2 = (trunc_ln47_3_fu_706_p4 + zext_ln47_5_fu_729_p1);

assign add_ln47_fu_536_p2 = (trunc_ln47_1_fu_509_p4 + zext_ln47_2_fu_532_p1);

assign add_ln59_1_fu_1195_p2 = (trunc_ln2_fu_1143_p4 + zext_ln59_fu_1191_p1);

assign add_ln59_fu_1129_p2 = ($signed(sext_ln59_fu_1126_p1) + $signed(zext_ln59_1_fu_1123_p1));

assign add_ln60_fu_1337_p2 = (trunc_ln3_fu_1285_p4 + zext_ln60_fu_1333_p1);

assign add_ln67_fu_1042_p2 = (trunc_ln4_fu_1012_p4 + zext_ln67_fu_1038_p1);

assign add_ln68_fu_1416_p2 = (trunc_ln5_reg_1693 + zext_ln68_fu_1413_p1);

assign and_ln44_1_fu_440_p2 = (xor_ln44_3_fu_410_p2 & or_ln44_3_fu_434_p2);

assign and_ln44_fu_349_p2 = (xor_ln44_fu_319_p2 & or_ln44_1_fu_343_p2);

assign and_ln47_10_fu_872_p2 = (tmp_20_fu_739_p3 & select_ln47_5_fu_822_p3);

assign and_ln47_11_fu_884_p2 = (xor_ln47_11_fu_878_p2 & empty_14_fu_842_p2);

assign and_ln47_1_fu_619_p2 = (xor_ln47_1_fu_613_p2 & icmp_ln47_fu_578_p2);

assign and_ln47_2_fu_633_p2 = (icmp_ln47_1_fu_593_p2 & and_ln47_fu_556_p2);

assign and_ln47_3_fu_669_p2 = (xor_ln47_4_fu_663_p2 & or_ln47_fu_657_p2);

assign and_ln47_4_fu_675_p2 = (tmp_10_fu_542_p3 & select_ln47_1_fu_625_p3);

assign and_ln47_5_fu_687_p2 = (xor_ln47_5_fu_681_p2 & empty_fu_645_p2);

assign and_ln47_6_fu_753_p2 = (xor_ln47_6_fu_747_p2 & tmp_19_fu_722_p3);

assign and_ln47_7_fu_816_p2 = (xor_ln47_7_fu_810_p2 & icmp_ln47_3_fu_775_p2);

assign and_ln47_8_fu_830_p2 = (icmp_ln47_4_fu_790_p2 & and_ln47_6_fu_753_p2);

assign and_ln47_9_fu_866_p2 = (xor_ln47_10_fu_860_p2 & or_ln47_2_fu_854_p2);

assign and_ln47_fu_556_p2 = (xor_ln47_fu_550_p2 & tmp_9_fu_525_p3);

assign and_ln59_1_fu_1265_p2 = (icmp_ln59_1_fu_1211_p2 & empty_15_fu_1245_p2);

assign and_ln59_fu_1185_p2 = (tmp_22_fu_1135_p3 & or_ln59_fu_1179_p2);

assign and_ln60_1_fu_1407_p2 = (icmp_ln60_1_fu_1353_p2 & empty_18_fu_1387_p2);

assign and_ln60_fu_1327_p2 = (tmp_26_fu_1277_p3 & or_ln60_fu_1321_p2);

assign and_ln67_fu_1074_p2 = (xor_ln67_fu_1068_p2 & tmp_32_fu_1030_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign brmerge2571_fu_1490_p2 = (xor_ln59_1_fu_1469_p2 | or_ln59_2_fu_1485_p2);

assign brmerge3083_fu_1538_p2 = (xor_ln60_1_fu_1517_p2 | or_ln60_2_fu_1533_p2);

assign empty_14_fu_842_p2 = (xor_ln47_8_fu_836_p2 & tmp_17_fu_699_p3);

assign empty_15_fu_1245_p2 = (xor_ln59_fu_1231_p2 & tmp_24_fu_1171_p3);

assign empty_16_fu_1251_p3 = ((tmp_24_fu_1171_p3[0:0] == 1'b1) ? select_ln59_fu_1237_p3 : icmp_ln59_2_fu_1217_p2);

assign empty_17_fu_1496_p3 = ((tmp_22_reg_1703[0:0] == 1'b1) ? select_ln59_1_fu_1479_p3 : add_ln59_1_reg_1709);

assign empty_18_fu_1387_p2 = (xor_ln60_fu_1373_p2 & tmp_28_fu_1313_p3);

assign empty_19_fu_1393_p3 = ((tmp_28_fu_1313_p3[0:0] == 1'b1) ? select_ln60_fu_1379_p3 : icmp_ln60_2_fu_1359_p2);

assign empty_20_fu_1544_p3 = ((tmp_26_reg_1728[0:0] == 1'b1) ? select_ln60_1_fu_1527_p3 : add_ln60_reg_1734);

assign empty_21_fu_1062_p2 = (tmp_33_fu_1048_p3 | not_tmp_38_fu_1056_p2);

assign empty_22_fu_1435_p2 = (xor_ln68_fu_1429_p2 & tmp_34_reg_1686);

assign empty_23_fu_1453_p3 = ((tmp_34_reg_1686[0:0] == 1'b1) ? select_ln68_fu_1440_p3 : add_ln68_fu_1416_p2);

assign empty_fu_645_p2 = (xor_ln47_2_fu_639_p2 & tmp_5_fu_502_p3);

assign grp_fu_1565_p0 = grp_fu_1565_p00;

assign grp_fu_1565_p00 = pivo_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik;

assign grp_fu_1565_p1 = 34'd17179866324;

assign grp_fu_1575_p1 = 36'd16158;

assign grp_fu_1586_p2 = 40'd52668;

assign grp_fu_1601_p2 = 42'd206178;

assign icmp_ln47_1_fu_593_p2 = ((tmp_3_fu_584_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln47_2_fu_599_p2 = ((tmp_3_fu_584_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln47_3_fu_775_p2 = ((tmp_6_fu_766_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln47_4_fu_790_p2 = ((tmp_7_fu_781_p4 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln47_5_fu_796_p2 = ((tmp_7_fu_781_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_578_p2 = ((tmp_2_fu_569_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln50_1_fu_972_p2 = (($signed(select_ln47_7_fu_962_p3) > $signed(22'd622592)) ? 1'b1 : 1'b0);

assign icmp_ln50_2_fu_978_p2 = (($signed(select_ln47_7_fu_962_p3) < $signed(22'd3571712)) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_913_p2 = (($signed(select_ln47_3_fu_903_p3) > $signed(22'd2080768)) ? 1'b1 : 1'b0);

assign icmp_ln59_1_fu_1211_p2 = ((tmp_s_fu_1201_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln59_2_fu_1217_p2 = ((tmp_s_fu_1201_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_1165_p2 = ((trunc_ln59_fu_1161_p1 != 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_1_fu_1353_p2 = ((tmp_29_fu_1343_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln60_2_fu_1359_p2 = ((tmp_29_fu_1343_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_1307_p2 = ((trunc_ln60_fu_1303_p1 != 13'd0) ? 1'b1 : 1'b0);

assign mul_ln44_1_fu_236_p1 = 36'd7188;

assign not_tmp_38_fu_1056_p2 = (tmp_32_fu_1030_p3 ^ 1'd1);

assign or_ln44_1_fu_343_p2 = (xor_ln44_2_fu_337_p2 | tmp_4_fu_311_p3);

assign or_ln44_2_fu_416_p2 = (xor_ln44_3_fu_410_p2 | tmp_16_fu_402_p3);

assign or_ln44_3_fu_434_p2 = (xor_ln44_5_fu_428_p2 | tmp_16_fu_402_p3);

assign or_ln44_fu_325_p2 = (xor_ln44_fu_319_p2 | tmp_4_fu_311_p3);

assign or_ln47_1_fu_693_p2 = (and_ln47_5_fu_687_p2 | and_ln47_3_fu_669_p2);

assign or_ln47_2_fu_854_p2 = (xor_ln47_9_fu_848_p2 | tmp_20_fu_739_p3);

assign or_ln47_3_fu_890_p2 = (and_ln47_9_fu_866_p2 | and_ln47_11_fu_884_p2);

assign or_ln47_fu_657_p2 = (xor_ln47_3_fu_651_p2 | tmp_10_fu_542_p3);

assign or_ln50_1_fu_992_p2 = (icmp_ln50_2_fu_978_p2 | icmp_ln50_1_fu_972_p2);

assign or_ln50_fu_935_p2 = (tmp_12_fu_919_p3 | icmp_ln50_fu_913_p2);

assign or_ln59_1_fu_1259_p2 = (tmp_22_fu_1135_p3 | empty_16_fu_1251_p3);

assign or_ln59_2_fu_1485_p2 = (xor_ln59_2_fu_1474_p2 & tmp_22_reg_1703);

assign or_ln59_fu_1179_p2 = (tmp_23_fu_1153_p3 | icmp_ln59_fu_1165_p2);

assign or_ln60_1_fu_1401_p2 = (tmp_26_fu_1277_p3 | empty_19_fu_1393_p3);

assign or_ln60_2_fu_1533_p2 = (xor_ln60_2_fu_1522_p2 & tmp_26_reg_1728);

assign or_ln60_fu_1321_p2 = (tmp_27_fu_1295_p3 | icmp_ln60_fu_1307_p2);

assign or_ln68_1_fu_1448_p2 = (tmp_36_fu_1421_p3 & tmp_34_reg_1686);

assign select_ln44_1_fu_446_p3 = ((and_ln44_1_fu_440_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln44_3_fu_396_p2);

assign select_ln44_fu_355_p3 = ((and_ln44_fu_349_p2[0:0] == 1'b1) ? 22'd2097151 : add_ln44_1_fu_305_p2);

assign select_ln47_1_fu_625_p3 = ((and_ln47_fu_556_p2[0:0] == 1'b1) ? and_ln47_1_fu_619_p2 : icmp_ln47_1_fu_593_p2);

assign select_ln47_2_fu_896_p3 = ((and_ln47_3_reg_1651[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln47_3_fu_903_p3 = ((or_ln47_1_reg_1656[0:0] == 1'b1) ? select_ln47_2_fu_896_p3 : add_ln47_reg_1646);

assign select_ln47_4_fu_802_p3 = ((and_ln47_6_fu_753_p2[0:0] == 1'b1) ? icmp_ln47_4_fu_790_p2 : icmp_ln47_5_fu_796_p2);

assign select_ln47_5_fu_822_p3 = ((and_ln47_6_fu_753_p2[0:0] == 1'b1) ? and_ln47_7_fu_816_p2 : icmp_ln47_4_fu_790_p2);

assign select_ln47_6_fu_955_p3 = ((and_ln47_9_reg_1666[0:0] == 1'b1) ? 22'd2097151 : 22'd2097152);

assign select_ln47_7_fu_962_p3 = ((or_ln47_3_reg_1671[0:0] == 1'b1) ? select_ln47_6_fu_955_p3 : add_ln47_1_reg_1661);

assign select_ln47_fu_605_p3 = ((and_ln47_fu_556_p2[0:0] == 1'b1) ? icmp_ln47_1_fu_593_p2 : icmp_ln47_2_fu_599_p2);

assign select_ln50_1_fu_984_p3 = ((icmp_ln50_1_fu_972_p2[0:0] == 1'b1) ? 21'd622592 : 21'd1474560);

assign select_ln50_fu_927_p3 = ((icmp_ln50_fu_913_p2[0:0] == 1'b1) ? 21'd2080768 : 21'd0);

assign select_ln59_1_fu_1479_p3 = ((and_ln59_1_reg_1722[0:0] == 1'b1) ? add_ln59_1_reg_1709 : 7'd0);

assign select_ln59_2_fu_1502_p3 = ((or_ln59_1_reg_1716[0:0] == 1'b1) ? empty_17_fu_1496_p3 : 7'd127);

assign select_ln59_fu_1237_p3 = ((tmp_25_fu_1223_p3[0:0] == 1'b1) ? icmp_ln59_2_fu_1217_p2 : icmp_ln59_1_fu_1211_p2);

assign select_ln60_1_fu_1527_p3 = ((and_ln60_1_reg_1747[0:0] == 1'b1) ? add_ln60_reg_1734 : 7'd0);

assign select_ln60_2_fu_1550_p3 = ((or_ln60_1_reg_1741[0:0] == 1'b1) ? empty_20_fu_1544_p3 : 7'd127);

assign select_ln60_fu_1379_p3 = ((tmp_30_fu_1365_p3[0:0] == 1'b1) ? icmp_ln60_2_fu_1359_p2 : icmp_ln60_1_fu_1353_p2);

assign select_ln67_fu_1080_p3 = ((empty_21_fu_1062_p2[0:0] == 1'b1) ? add_ln67_fu_1042_p2 : 7'd127);

assign select_ln68_fu_1440_p3 = ((empty_22_fu_1435_p2[0:0] == 1'b1) ? add_ln68_fu_1416_p2 : 7'd0);

assign sext_ln44_2_fu_246_p0 = pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik;

assign sext_ln44_2_fu_246_p1 = sext_ln44_2_fu_246_p0;

assign sext_ln44_5_fu_258_p1 = $signed(tmp_13_fu_250_p3);

assign sext_ln59_fu_1126_p1 = uv_aux_reg_1681;

assign sub_ln44_1_fu_268_p2 = ($signed(sub_ln44_fu_262_p2) - $signed(sext_ln44_2_fu_246_p1));

assign sub_ln44_fu_262_p2 = ($signed(27'd0) - $signed(sext_ln44_5_fu_258_p1));

assign sub_ln47_2_fu_489_p2 = (zext_ln47_3_fu_481_p1 - zext_ln47_4_fu_485_p1);

assign sub_ln47_fu_468_p2 = (zext_ln47_fu_460_p1 - zext_ln47_1_fu_464_p1);

assign sub_ln60_fu_1271_p2 = ($signed(zext_ln59_1_fu_1123_p1) - $signed(sext_ln59_fu_1126_p1));

assign tmp_10_fu_542_p3 = add_ln47_fu_536_p2[32'd21];

assign tmp_11_fu_562_p3 = grp_fu_1586_p3[32'd36];

assign tmp_12_fu_919_p3 = select_ln47_3_fu_903_p3[32'd21];

assign tmp_13_fu_250_p1 = pivf_fun_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_xUik;

assign tmp_13_fu_250_p3 = {{tmp_13_fu_250_p1}, {4'd0}};

assign tmp_14_fu_369_p3 = grp_fu_1575_p3[32'd35];

assign tmp_15_fu_385_p3 = grp_fu_1575_p3[32'd13];

assign tmp_16_fu_402_p3 = add_ln44_3_fu_396_p2[32'd21];

assign tmp_17_fu_699_p3 = grp_fu_1601_p3[32'd41];

assign tmp_18_fu_715_p3 = grp_fu_1601_p3[32'd13];

assign tmp_19_fu_722_p3 = grp_fu_1601_p3[32'd35];

assign tmp_1_fu_294_p3 = grp_fu_1565_p3[32'd13];

assign tmp_20_fu_739_p3 = add_ln47_1_fu_733_p2[32'd21];

assign tmp_21_fu_759_p3 = grp_fu_1601_p3[32'd36];

assign tmp_22_fu_1135_p3 = add_ln59_fu_1129_p2[32'd22];

assign tmp_23_fu_1153_p3 = add_ln59_fu_1129_p2[32'd13];

assign tmp_24_fu_1171_p3 = add_ln59_fu_1129_p2[32'd20];

assign tmp_25_fu_1223_p3 = add_ln59_1_fu_1195_p2[32'd6];

assign tmp_26_fu_1277_p3 = sub_ln60_fu_1271_p2[32'd22];

assign tmp_27_fu_1295_p3 = sub_ln60_fu_1271_p2[32'd13];

assign tmp_28_fu_1313_p3 = sub_ln60_fu_1271_p2[32'd20];

assign tmp_29_fu_1343_p4 = {{sub_ln60_fu_1271_p2[22:21]}};

assign tmp_2_fu_569_p4 = {{grp_fu_1586_p3[39:37]}};

assign tmp_30_fu_1365_p3 = add_ln60_fu_1337_p2[32'd6];

assign tmp_31_fu_1022_p3 = ui_aux_fu_941_p3[32'd13];

assign tmp_32_fu_1030_p3 = ui_aux_fu_941_p3[32'd20];

assign tmp_33_fu_1048_p3 = add_ln67_fu_1042_p2[32'd6];

assign tmp_36_fu_1421_p3 = add_ln68_fu_1416_p2[32'd6];

assign tmp_3_fu_584_p4 = {{grp_fu_1586_p3[39:36]}};

assign tmp_4_fu_311_p3 = add_ln44_1_fu_305_p2[32'd21];

assign tmp_5_fu_502_p3 = grp_fu_1586_p3[32'd39];

assign tmp_6_fu_766_p4 = {{grp_fu_1601_p3[41:37]}};

assign tmp_7_fu_781_p4 = {{grp_fu_1601_p3[41:36]}};

assign tmp_8_fu_518_p3 = grp_fu_1586_p3[32'd13];

assign tmp_9_fu_525_p3 = grp_fu_1586_p3[32'd35];

assign tmp_fu_278_p3 = grp_fu_1565_p3[32'd35];

assign tmp_s_fu_1201_p4 = {{add_ln59_fu_1129_p2[22:21]}};

assign trunc_ln2_fu_1143_p4 = {{add_ln59_fu_1129_p2[20:14]}};

assign trunc_ln3_fu_1285_p4 = {{sub_ln60_fu_1271_p2[20:14]}};

assign trunc_ln44_3_fu_376_p4 = {{grp_fu_1575_p3[35:14]}};

assign trunc_ln47_1_fu_509_p4 = {{grp_fu_1586_p3[35:14]}};

assign trunc_ln47_3_fu_706_p4 = {{grp_fu_1601_p3[35:14]}};

assign trunc_ln4_fu_1012_p4 = {{ui_aux_fu_941_p3[20:14]}};

assign trunc_ln50_1_fu_968_p1 = select_ln47_7_fu_962_p3[20:0];

assign trunc_ln50_fu_909_p1 = select_ln47_3_fu_903_p3[20:0];

assign trunc_ln59_fu_1161_p1 = add_ln59_fu_1129_p2[12:0];

assign trunc_ln60_fu_1303_p1 = sub_ln60_fu_1271_p2[12:0];

assign trunc_ln_fu_285_p4 = {{grp_fu_1565_p3[35:14]}};

assign ui = ((and_ln67_fu_1074_p2[0:0] == 1'b1) ? select_ln67_fu_1080_p3 : add_ln67_fu_1042_p2);

assign ui_aux_fu_941_p3 = ((or_ln50_fu_935_p2[0:0] == 1'b1) ? select_ln50_fu_927_p3 : trunc_ln50_fu_909_p1);

assign uv = ((or_ln68_1_fu_1448_p2[0:0] == 1'b1) ? empty_23_fu_1453_p3 : add_ln68_fu_1416_p2);

assign uv_aux_fu_998_p3 = ((or_ln50_1_fu_992_p2[0:0] == 1'b1) ? select_ln50_1_fu_984_p3 : trunc_ln50_1_fu_968_p1);

assign xor_ln44_1_fu_331_p2 = (tmp_fu_278_p3 ^ or_ln44_fu_325_p2);

assign xor_ln44_2_fu_337_p2 = (xor_ln44_1_fu_331_p2 ^ 1'd1);

assign xor_ln44_3_fu_410_p2 = (tmp_14_fu_369_p3 ^ 1'd1);

assign xor_ln44_4_fu_422_p2 = (tmp_14_fu_369_p3 ^ or_ln44_2_fu_416_p2);

assign xor_ln44_5_fu_428_p2 = (xor_ln44_4_fu_422_p2 ^ 1'd1);

assign xor_ln44_fu_319_p2 = (tmp_fu_278_p3 ^ 1'd1);

assign xor_ln47_10_fu_860_p2 = (tmp_17_fu_699_p3 ^ 1'd1);

assign xor_ln47_11_fu_878_p2 = (1'd1 ^ and_ln47_10_fu_872_p2);

assign xor_ln47_1_fu_613_p2 = (tmp_11_fu_562_p3 ^ 1'd1);

assign xor_ln47_2_fu_639_p2 = (1'd1 ^ and_ln47_2_fu_633_p2);

assign xor_ln47_3_fu_651_p2 = (select_ln47_fu_605_p3 ^ 1'd1);

assign xor_ln47_4_fu_663_p2 = (tmp_5_fu_502_p3 ^ 1'd1);

assign xor_ln47_5_fu_681_p2 = (1'd1 ^ and_ln47_4_fu_675_p2);

assign xor_ln47_6_fu_747_p2 = (tmp_20_fu_739_p3 ^ 1'd1);

assign xor_ln47_7_fu_810_p2 = (tmp_21_fu_759_p3 ^ 1'd1);

assign xor_ln47_8_fu_836_p2 = (1'd1 ^ and_ln47_8_fu_830_p2);

assign xor_ln47_9_fu_848_p2 = (select_ln47_4_fu_802_p3 ^ 1'd1);

assign xor_ln47_fu_550_p2 = (tmp_10_fu_542_p3 ^ 1'd1);

assign xor_ln59_1_fu_1469_p2 = (or_ln59_1_reg_1716 ^ 1'd1);

assign xor_ln59_2_fu_1474_p2 = (1'd1 ^ and_ln59_1_reg_1722);

assign xor_ln59_fu_1231_p2 = (tmp_25_fu_1223_p3 ^ 1'd1);

assign xor_ln60_1_fu_1517_p2 = (or_ln60_1_reg_1741 ^ 1'd1);

assign xor_ln60_2_fu_1522_p2 = (1'd1 ^ and_ln60_1_reg_1747);

assign xor_ln60_fu_1373_p2 = (tmp_30_fu_1365_p3 ^ 1'd1);

assign xor_ln67_fu_1068_p2 = (tmp_33_fu_1048_p3 ^ 1'd1);

assign xor_ln68_fu_1429_p2 = (tmp_36_fu_1421_p3 ^ 1'd1);

assign zext_ln44_1_fu_301_p1 = tmp_1_fu_294_p3;

assign zext_ln44_2_fu_392_p1 = tmp_15_fu_385_p3;

assign zext_ln47_1_fu_464_p1 = Vout;

assign zext_ln47_2_fu_532_p1 = tmp_8_fu_518_p3;

assign zext_ln47_3_fu_481_p1 = Vfcref;

assign zext_ln47_4_fu_485_p1 = Vfc;

assign zext_ln47_5_fu_729_p1 = tmp_18_fu_715_p3;

assign zext_ln47_fu_460_p1 = Voutref;

assign zext_ln59_1_fu_1123_p1 = ui_aux_reg_1676;

assign zext_ln59_fu_1191_p1 = and_ln59_fu_1185_p2;

assign zext_ln60_fu_1333_p1 = and_ln60_fu_1327_p2;

assign zext_ln67_fu_1038_p1 = tmp_31_fu_1022_p3;

assign zext_ln68_fu_1413_p1 = tmp_35_reg_1698;

endmodule //fcc
